### ISSUE TITLE
RuntimeError: Error building extension 'wkv_cuda_v1'

### ISSUE THREAD

**Issue by Spr-Peach** [v3ucn/RWKV_3B_7B_Webui_GPT-SoVITS#1]
please help me, even if I use conda create venv with python==10.11 cuda=11.9or12.1 and torch=2.2.1, it was always showed the RuntimeError: Error building extension 'wkv_cuda_v1'
```
......

注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\structseq.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\namespaceobject.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/picklebufobject.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/pytime.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\codecs.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\pyerrors.h
注意: 包含文件:        C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/pyerrors.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\pythread.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\context.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\modsupport.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\compile.h
注意: 包含文件:        C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/compile.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\pythonrun.h
注意: 包含文件:        C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/pythonrun.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\pylifecycle.h
注意: 包含文件:        C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/pylifecycle.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\ceval.h
注意: 包含文件:        C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/ceval.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\sysmodule.h
注意: 包含文件:        C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/sysmodule.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\osmodule.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\intrcheck.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\import.h
注意: 包含文件:        C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/import.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\bltinmodule.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\eval.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/pyctype.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\pystrtod.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\pystrcmp.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\fileutils.h
注意: 包含文件:        C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/fileutils.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/pyfpe.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\tracemalloc.h
注意: 包含文件:      C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\frameobject.h
注意: 包含文件:       C:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include\cpython/frameobject.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/Dtype.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/DynamicTypes.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/Exceptions.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\ATen/detail/FunctionTraits.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11/pybind11.h
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail/class.h
注意: 包含文件:       C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail\../attr.h
注意: 包含文件:        C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail/common.h
注意: 包含文件:         C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\version
注意: 包含文件:        C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\cast.h
注意: 包含文件:         C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail/descr.h
注意: 包含文件:         C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail/type_caster_base.h
注意: 包含文件:          C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail\../pytypes.h
注意: 包含文件:           C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\buffer_info.h
注意: 包含文件:           C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\assert.h
注意: 包含文件:          C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail\internals.h
注意: 包含文件:          C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail\typeid.h
注意: 包含文件:       C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail\../options.h
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\detail/init.h
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11\gil.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/jit/runtime/jit_exception.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/utils/cpp_stacktraces.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/utils/pybind.h
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\pybind11/stl.h
注意: 包含文件:       C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\valarray
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/Generator.h
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/MemoryFormat.h
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/Stream.h
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/utils/tensor_memoryformats.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/autograd/python_variable.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/utils/pythoncapi_compat.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/utils/python_numbers.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/jit/frontend/tracer.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/utils/object_ptr.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/utils/tensor_numpy.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch/csrc/utils/python_tuples.h
注意: 包含文件:  C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDAGuard.h
注意: 包含文件:   C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDAMacros.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/impl/cuda_cmake_macros.h
注意: 包含文件:   C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/impl/CUDAGuardImpl.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/core/impl/GPUTrace.h
注意: 包含文件:    C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDACachingAllocator.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDAGraphsC10Utils.h
注意: 包含文件:      C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDAStream.h
注意: 包含文件:       C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\cuda_runtime_api.h
注意: 包含文件:        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_defines.h
注意: 包含文件:        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\builtin_types.h
注意: 包含文件:         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\device_types.h
注意: 包含文件:          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_defines.h
注意: 包含文件:         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\driver_types.h
注意: 包含文件:          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_defines.h
注意: 包含文件:          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\vector_types.h
注意: 包含文件:           C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_defines.h
注意: 包含文件:         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\surface_types.h
注意: 包含文件:          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\driver_types.h
注意: 包含文件:         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\texture_types.h
注意: 包含文件:          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\driver_types.h
注意: 包含文件:         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\vector_types.h
注意: 包含文件:        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\cuda_device_runtime_api.h
注意: 包含文件:       C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDAFunctions.h
注意: 包含文件:        C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDAException.h
注意: 包含文件:         C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDADeviceAssertionHost.h
注意: 包含文件:         C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/cuda/CUDAMiscFunctions.h
注意: 包含文件:         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\cuda.h
注意: 包含文件:        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\cuda_runtime_api.h
注意: 包含文件:     C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\c10/util/ApproximateClock.h
注意: 包含文件:    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\cuda_runtime_api.h
[2/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output operators.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=wkv_cuda_v1 -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include -IC:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\TH -IC:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\namiachy\AppData\Local\Programs\Python\Python310\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 --use_fast_math -O3 --extra-device-vectorization -c C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\rwkv\cuda\operators.cu -o operators.cuda.o
operators.cu
[3/3] "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64/link.exe" wrapper.o operators.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:wkv_cuda_v1.pyd
FAILED: wkv_cuda_v1.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64/link.exe" wrapper.o operators.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:wkv_cuda_v1.pyd
LINK : fatal error LNK1104: 无法打开文件“python310.lib”
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2096, in _run_ninja_build
    subprocess.run(
  File "C:\Users\namiachy\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\rwkv\model.py", line 32, in <module>
    load(
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_cuda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2096, in _run_ninja_build
    subprocess.run(
  File "C:\Users\namiachy\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\webui_gpu.py", line 42, in <module>
    from rwkv.model import RWKV
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\rwkv\model.py", line 42, in <module>
    load(
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_cuda_v1'

(venv) C:\Users\namiachy\RWKV_3B_7B_Webui_GPT-SoVITS>
```

**Comment by Spr-Peach** [comment]
and when i used the bat file:
```
Active code page: 65001
The system cannot find the path specified.
请按任意键继续
Press any key to continue . . .
```
